### ISSUE TITLE
Compiled IR ordering not stable

### ISSUE THREAD

**Issue by bmoylan** [palantir/godel-conjure-plugin#26]
Confirmed with Felipe that the conjure IR compiler can not be trusted to give 100% reproducible ordering, which results in reordered generated code and a failed `verify` task.

Generating based on published IR should not be affected.

**Comment by nmiyake** [comment]
Can we file an issue on the IR compiler and cross-reference here? I feel like the IR compiler should strive to generate deterministic output.

**Comment by bmoylan** [comment]
https://github.com/palantir/conjure/issues/316
